### PR TITLE
Port to listen 3

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by alexch** [comment]
It seems like you've removed the ability to know which adapter it's using. Any way to get that feature back?

**Comment by terceiro** [comment]
as far as I understand this is now treated as private in listen, so you should not be able to access that. it should be something like `@listener.backend.adapter`, however the `adapter` method is private in listen's Backend class.

**Comment by strzibny** [comment]
I tested this patch both with listen 2 and listen 3 and it works for me. Exactly what I need now (so we can update listen in Fedora). Please merge.

**Comment by alexch** [comment]
Will do. And then try to get that message back.

**Comment by bswinnerton** [comment]
:+1: much thanks for the fix. This was causing problems when trying to run a rack application with Sidekiq (which depends on Celluloid):

```
I, [2015-09-19T09:39:17.727652 #21325]  INFO -- : Celluloid 0.17.1.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
Puma 2.13.4 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
/Users/brooks/Sites/babblings-api/vendor/bundle/gems/celluloid-0.17.1.2/lib/celluloid/calls.rb:48:in `check': wrong number of arguments (2 for 1) (ArgumentError)
```
(Stack trace for posterity's sake)

Any chance we could get a new version of the gem cut for this PR? It's resolved the issue for me.

**Pull request merged**
